accounts/urls.py
from django.urls import path,include
from django.contrib.auth.views import (
    LoginView, LogoutView,)
from .views import *
from tech.views import news_home
# from django.conf import settings
# from django.conf.urls.static import static
app_name = 'accounts'
urlpatterns = [
    # path('register/', register, name='register'),
    path('sign_up/', MySignUpView.as_view(), name='sign_up'),
    path('profile/', profile, name='profile'),
    path('interest/', interest, name='interest'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name="login"),
    path('news_upload/', news_upload, name='news_upload'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name="logout"),
    path('',news_home,name='news_home'),
    # path('',include('new.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from tech.views import news_home,about,homepage
from accounts.views import MySignUpView
from django.contrib.auth import views as auth_views
#from .views import upload

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('tech/', include('tech.urls')),
    path('sign_up/', MySignUpView.as_view(), name='sign_up'),

    #path('',upload,name='upload'),
    path('about/',about,name='about'),
    path('news_home/',news_home,name='news_home'),
    path('',homepage,name='homepage'),
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name="final/password_reset_form.html"),name='reset_password'),
    path('reset_password_sent',auth_views.PasswordResetDoneView.as_view(template_name="final/password_reset_done.html"),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="final/password_reset_confirm.html"),name='password_reset_confirm'),
    path('reset_password_complete',auth_views.PasswordResetCompleteView.as_view(template_name="final/password_reset_complete.html"),name='password_reset_complete'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tech/urls.py
from django.urls import path

from .views import *

app_name='tech'

urlpatterns = [
    path('news/',news_home,name='home'),
    path('detail/',news_detail,name='detail'),
    path('about/',about,name='about'),
    path('rate/',rate_show,name='rate'),
    path('',homepage,name='homepage'),

    #path('upload/',upload,name='upload'),
]

tech/models.py
from django.db import models

# Create your models here.
class News(models.Model):
    news_id=models.CharField(max_length=10)
    news_title=models.CharField(max_length=100)
    news_genre=models.CharField(max_length=100)
    news_plot=models.CharField(max_length=2000)
    #news_author=models.CharField(max_length=100)
    news_link=models.CharField(max_length=200)
    news_rating=models.CharField(max_length=100)
    views=models.IntegerField(max_length=5000,default=0)

    def __str__(self):
        return self.news_title

class News_Rating(models.Model):
    username = models.CharField(max_length=100)
    news_title = models.CharField(max_length=100)
    rating=models.FloatField()

tech/views.py
from django.shortcuts import render
#import csv,io 
# Create your views here.
from django.http import HttpResponse
#from django.contrib import messages
from . import utils
from .models import News_Rating,News
from accounts.models import Profile
from django.contrib.auth.decorators import login_required



def homepage(request):
    popular_news=utils.popular_news()    
    data={}
    data['popular_news']=popular_news
    return render(request,"tech/home.html",data)

@login_required
def news_home(request):
    data={}
    obj= Profile.objects.filter(user=request.user).first()
    dominelist=obj.interest
    popular_news=utils.popular_news()
    personalized=utils.personalized_shows(str(request.user),request)
    if 'python' in dominelist:
        python=utils.top_charts("python")
        data['python']=python
    if 'ml' in dominelist:
        ml=utils.top_charts("ml")
        data['ml']=ml
    if 'JS' in dominelist:
        JS=utils.top_charts("JS")
        data['JS']=JS
    if 'java' in dominelist:
        java=utils.top_charts("java")
        data['java']=java
    if 'hacking' in dominelist:
        hacking=utils.top_charts("hacking")
        data['hacking']=hacking 
    data['popular_news']=popular_news 
    data['personalized']=personalized
    #TODO render code
    return render(request,'tech/tech.html',data)

def news_detail(request):
    title=request.GET['title']
    news_data=utils.get_news_details(title)
    similar_news=utils.similar_shows(title,request)
    data={}

    data['already_rated'] = False
    data['rating_value'] = 0
    qSet = News_Rating.objects.filter(username=str(request.user))

    for q in qSet:
        if q.news_title == news_data["news_title"]:
            data['already_rated'] = True
            data['rating_value'] = str(q.rating)

    data['news_data']=news_data
    data['similar_news']=similar_news
   

    #TODO render code
    return render(request,'tech/tech_details.html',data)

@login_required
def rate_show(request):
    username=str(request.user)
    news_title=request.GET["news_title"]
    rating=request.GET["rating"]
    utils.rate_show(username,news_title,rating)
    #TODO render code
    return HttpResponse("{'message':'success'}")

@login_required
def about(request):
    data={}
    return render(request,'tech/about.html',data)

tech/templates/tech/about.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css"href="{% static 'tech/main.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <title>posts</title>
</head>
<body>
  <!-- Navbar -->
  <div class="navbar">
    <div class="container flex">
      <h1 class="logo">Tech News</h1>
      <nav>
        <ul>
          <li><a href="{% url 'news_home' %}">Home</a></li>
          <li><a href="{% url 'tech:about'%}">About</a></li>
          <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
          
        </ul>
      </nav>
    </div>
  </div>
    <center>
  <section>
      <h1 class="text">Personalized Recommendation </h1>
      <small>using Machine Learning</small>
  </section>
</center>
</body>
</html>

tech/templates/tech/home.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css"href="{% static 'tech/home.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link
      href="https://fonts.googleapis.com/css?family=Oswald:700|Poppins"
      rel="stylesheet"
    />
    <title>Tech News</title>
</head>
<body>
  <div class="cursor"></div>
    <div class="navbar">
        <div class="container flex">
          <div class="logos flex">
            <img class="img-logo" src="{%static 'tech/logo.png'%}" alt="">
          </div>
          <div class="nav-items">
            <nav>
              <ul class="nav-links">
                <li><a href="#about">About</a></li>
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:sign_up' %}">Sign Up</a></li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
      <section class="home">
          <aside class="side-section">
              <div class="side-items">
                <h3>Popular Tags</h3>
                    <p>#js</p>
                    <p>#python</p>
                    <p>#ml</p>
              </div>
          </aside>
          <main>
              <div class="python-code">
              <p><span class="if">if</span><span class="statement"> "Syntax error" :</span></p>
              <p class="print"> <span class="orange">print</span> ("Learn more.")</p>
              <p class="elif"> <span class="if"> elif </span> <span class="statement">"Compilation error" :</span> </p>
              <p class="print"> <span class="orange">print</span> ("Code more.")</p>
              <p class="if else">else :</p>
              <p class="print"> <span class="orange">print</span> ("Do more.")</p>
            </div>
            <div class="explore">
              <h1>Explore.</h1>
            </div>
          </main>
      </section>
      
      <div class="home-posts">
        <ul class="post-lists">
          {% for q in popular_news%}
                      <li class="post">
                      <a class="post-title" href="{% url 'tech:detail' %}?title={{ q.news_title }}">                              
                        <h3 class="text-title">{{ q.news_title}}</h3>
                        <small>#{{q.news_genre}}</small>
                      </a>
                        <img width="250" height="300" class="post-cover" src="{{q.news_link}}" alt="cover" >
                        <p class="post-news">{{ q.news_plot }}</p>
                        
                      </li>
                  {% endfor %}
        </ul>
      </div>
      <footer>
        <h3 id="about">About Us</h3>
        <h1>We are Developers.</h1>
        <h3>Get in touch</h3><br>
      
        <small>  Email: <strong>suhasbdvt6@gmail.com</strong></small>
        

      </footer>
      <script type="text/javascript" src="{% static '/js/main.js' %}"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/latest/TweenMax.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/latest/plugins/ScrollToPlugin.min.js"></script>
    
</body>
</html>

tech/templates/tech/tech.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css"href="{% static 'tech/tech.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <title>posts</title>
</head>
<body>
  <div class="navbar">
      <div class="container flex">
        <div class="logos flex">
          <img class="img-logo" src="{%static 'tech/logo.png'%}" alt="">
        </div>
        <div class="nav-items">
          <nav>
            <ul>
              <li><a href="{% url 'news_home' %}">Home</a></li>
              <li><a href="{% url 'accounts:profile'%}">Profile</a></li>
              <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
    <section class="home">
        <aside class="side-section">
            <div class="side-items">
              <h3>Popular Tags</h3>
                  <p>#js</p>
                  <p>#python</p>
                  <p>#ml</p>
            </div>
        </aside>
        <main>
        
          <div class="content">
            <div class="post-section">
              {%if JS|length > 0 %}
                  <h3 class="topic">TOP JAVASCRIPT POSTS</h3>
                    <ul class="post-lists">
                    
                      {% for q in JS %}
                                  <li class="post">
                                  <a class="post-title" href="{% url 'tech:detail' %}?title={{ q.news_title }}">                              
                                    <h1 class="text">{{ q.news_title}}</h1>
                                  </a>
                                    <i class="fab fa-js icon js"></i>
                                    <p class="post-news">{{ q.news_plot }}</p>
                                  </li>
                              {% endfor %}
                        <!-- <small class="view-post">Open it</small>       -->
                    </ul>
              {% endif %}
              {%if ml|length > 0 %}
                    <h3 class="topic">TOP ML POSTS</h3>
                      <ul class="post-lists">
                        {% for q in ml%}
                          
                                    <li class="post">
                                    <a class="post-title" href="{% url 'tech:detail' %}?title={{ q.news_title }}">                              
                                      <h1 class="text">{{ q.news_title}}</h1>
                                    </a>
                                      <i class="fas fa-robot icon ml"></i>                                
                                      <p class="post-news">{{ q.news_plot }}</p>
                                    
                                    </li>
                                {% endfor %}
                      </ul>
              {%endif%}
                      {%if python|length > 0 %}
                      <h3 class="topic">TOP PYTHON POSTS</h3>
                        <ul class="post-lists">
                          {% for q in python%}
                            
                                      <li class="post">
                                      <a class="post-title" href="{% url 'tech:detail' %}?title={{ q.news_title }}">                              
                                        <h1 class="text">{{ q.news_title}}</h1>
                                      </a>
                                      <i class="fab fa-python python icon python"></i>                                  
                                      <p class="post-news">{{ q.news_plot }}</p>
                                      </li>
                                  {% endfor %}
                        </ul>
                        {%endif%}
                        {%if java|length > 0 %}
                        <h3 class="topic">TOP JAVA POSTS</h3>
                        <ul class="post-lists">
                          {% for q in java%}
                            
                                      <li class="post">
                                      <a class="post-title" href="{% url 'tech:detail' %}?title={{ q.news_title }}">                              
                                        <h1 class="text">{{ q.news_title}}</h1>
                                      </a>
                                      <i class="fab fa-java icon java"></i>                                
                                      <p class="post-news">{{ q.news_plot }}</p>
                                      </li>
                                  {% endfor %}
                        </ul>
                        {%endif%}
                        {%if hacking|length > 0 %}
                        <h3 class="topic">TOP HACKING POSTS</h3>
                        <ul class="post-lists">
                          {% for q in hacking%}
                            
                                      <li class="post">
                                      <a class="post-title" href="{% url 'tech:detail' %}?title={{ q.news_title }}">                              
                                        <h1 class="text">{{ q.news_title}}</h1>
                                      </a>
                                      <i class="fas fa-dragon icon hacking"></i>                                
                                      <p class="post-news">{{ q.news_plot }}</p>
                                      </li>
                                  {% endfor %}
                        </ul>
                        {%endif%}
            </div>
            <div class="recommended">
              <h3 class="topic">You might like</h3>
              <ul class="post-lists rec">
                {% for q in personalized%}
                <li class="post">
                  <a class="post-title" href="{% url 'tech:detail' %}?title={{ q.news_title }}">                              
                    <h1 class="text">{{ q.news_title}}</h1>
                  </a>
                {% if q.news_genre == 'python'%}
                <i class="fab fa-python python icon python"></i>
                {% elif q.news_genre == 'JS'%}
                <i class="fab fa-js icon js"></i>
                {% elif q.news_genre == 'ml' %}
                <i class="fas fa-robot icon ml"></i>  
                {% elif q.news_genre == 'java' %}    
                <i class="fab fa-java icon java"></i>                                
                {% elif q.news_genre == 'hacking' %}
                <i class="fas fa-dragon icon hacking"></i>                                                          
                {%endif%}                                       
                <p class="post-news">{{ q.news_plot }}</p>
                </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </main>
    </section>
</body>
</html>










































tech/templates/tech/tech_details.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css"href="{% static 'tech/home.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Tech News</title>
</head>
<body>
    <div class="navbar">
        <div class="container flex">
          <div class="logos flex">
            <img class="img-logo" src="{%static 'tech/logo.png'%}" alt="">
          </div>
          <div class="nav-items">
            <nav>
              <ul class="nav-links">
                {% if user.is_authenticated %}
                <li><a href="{% url 'tech:home' %}">Home</a></li>
                <li><a href="{% url 'accounts:profile'%}">Profile</a></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {%else%}  
                <li><a href="{% url 'homepage' %}">Home</a></li>          
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:sign_up' %}">Sign Up</a></li>
                {%endif%}
              </ul>
            </nav>
          </div>
        </div>
      </div>
           
          

  <section class="showcase">
    <div class="container">
      <div class="post-data">
        <h1 class="post-title">{{news_data.news_title}}</h1>
        <div class="img-container">
          <img class="post-img" src="{{news_data.news_link}}" alt="cover" >
        </div>
        <p class="post-news1">{{ news_data.news_plot }}</p>
      </div>

      <ul class="post-lists">
        {% for q in popular_news%}
                    <li class="post">
                    <a class="post-title" href="{% url 'tech:detail' %}?title={{ q.news_title }}">                              
                      <h3 class="text-title">{{ q.news_title}}</h3>
                      <small>#{{q.news_genre}}</small>
                    </a>
                      <img width="250" height="300" class="post-cover" src="{{q.news_link}}" alt="cover" >
                      <p class="post-news">{{ q.news_plot }}</p>
                      
                    </li>
        {% endfor %}
      </ul>

      {% if user.is_authenticated %}



      <div class="details">
        <div class="rat1">
        <small class="rate-text">Rate this post to help others</small>
        <fieldset class="rating">
          <input onclick="rateAjax(this.value)" type="radio" id="star5" name="rating" value="5" /><label class = "full" for="star5" title="5 stars"></label>
          <input onclick="rateAjax(this.value)" type="radio" id="star4half" name="rating" value="4.5" /><label class="half" for="star4half" title="4.5 stars"></label>
          <input onclick="rateAjax(this.value)" type="radio" id="star4" name="rating" value="4"/><label class = "full" for="star4" title="4 stars"></label>
          <input onclick="rateAjax(this.value)" type="radio" id="star3half" name="rating" value="3.5" /><label class="half" for="star3half" title="3.5 stars"></label>
          <input onclick="rateAjax(this.value)" type="radio" id="star3" name="rating" value="3" /><label class = "full" for="star3" title="3 stars"></label>
          <input onclick="rateAjax(this.value)" type="radio" id="star2half" name="rating" value="2.5" /><label class="half" for="star2half" title="2.5 stars"></label>
          <input onclick="rateAjax(this.value)" type="radio" id="star2" name="rating" value="2" /><label class = "full" for="star2" title="2 stars"></label>
          <input onclick="rateAjax(this.value)" type="radio" id="star1half" name="rating" value="1.5" /><label class="half" for="star1half" title="1.5 stars"></label>
          <input onclick="rateAjax(this.value)" type="radio" id="star1" name="rating" value="1" /><label class = "full" for="star1" title="1 star"></label>
          <input onclick="rateAjax(this.value)" type="radio" id="starhalf" name="rating" value="0.5" /><label class="half" for="starhalf" title="0.5 stars"></label>
        </fieldset>
      </div>
        <div class="rat2">
          <small>Your Rating</small>
        <p class="likes">  {{rating_value}}</p>
      </div>
    </div>
    </div>

        <div class="content">
          <div class="post-section">
      <h2 class="topic">Recommended Posts</h2>
      <ul class="post-lists">
        {% for q in similar_news %}
        <li class="post">
          <a class="post-title" href="{% url 'tech:detail' %}?title={{ q.news_title }}">                              
            <h1 class="text">{{ q.news_title}}</h1>
          </a>
        {% if q.news_genre == 'python'%}
        <i class="fab fa-python python icon python"></i>
        {% elif q.news_genre == 'JS'%}
        <i class="fab fa-js icon js"></i>
        {% elif q.news_genre == 'ml' %}
        <i class="fas fa-robot icon ml"></i>  
        {% elif q.news_genre == 'java' %}    
        <i class="fab fa-java icon java"></i>                                
        {% elif q.news_genre == 'hacking' %}
        <i class="fas fa-dragon icon hacking"></i>                                                          
        {%endif%}                                       
        <p class="post-news">{{ q.news_plot }}</p>
        </li>
        {% endfor %}
      </ul>
          </div>
        </div>
    </div>
    </div>
    {%endif%}
  </section>
  <script>
    
var id=getId("{{ rating_value }}");
elem=document.getElementById(id);
elem.checked=true;

function rateAjax(ratingValue){
    var url="{% url 'tech:rate' %}?news_title={{news_data.news_title}}&rating="+ratingValue;
          console.log(url)
          var req=new XMLHttpRequest();
          req.open('GET',url)
          req.onload=function()
          {
              console.log(req.responseText);
              alert("Success. Given "+ratingValue+" rating to {{ news_data.news_title }}.");
              location.reload();
          };
          req.send();
  }

  
  function getId(rating) {
    var ans=0;
    if(rating=='0.5'){
            ans='starhalf';
        }
        else if(rating=='1.0'){
            ans='star1';
        }
        else if(rating=='1.5') {
            ans = 'star1half'
        }
        else if(rating=='2.0'){
            ans='star2'
        }
        else if(rating=='2.5'){
            ans='star2half'
        }
        else if(rating=='3.0'){
            ans='star3'
        }
        else if(rating=='3.5'){
            ans='star3half'
        }
        else if(rating=='4.0'){
            ans='star4'
        }
        else if(rating=='4.5'){
            ans='star4half'
        }
        else if(rating=='5.0'){
            ans='star5'
        }
        return ans;
}

  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" integrity="sha512-RXf+QSDCUQs5uwRKaDoXt55jygZZm2V++WUZduaU/Ui/9EGp3f/2KZVahFZBKGH0s774sd3HmrhUy+SgOFQLVQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script type="text/javascript" src="{% static '/js/main.js' %}"></script>
</body>
</html>










































